/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />
// NOTE: This file is automatically generated by Next.js. Do not edit this file manually.

// Added to satisfy Next.js type-checking for server-side CSV rebuild endpoint.
declare module 'papaparse';
